/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.*;

import io.github.bonigarcia.wdm.WebDriverManager;

import static org.testng.Assert.*;

import java.time.Duration;
import java.util.List;
// import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

// import javax.swing.Action;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class AppTest{

    private WebDriver driver;
        private static final Logger logger = Logger.getLogger(AppTest.class.getName());
        private WebDriverWait wait;
        private Actions action;

    @BeforeTest
    public void setup() {
        WebDriverManager.chromiumdriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://www.amazon.com.mx/");

        wait = new WebDriverWait(driver, Duration.ofSeconds(5));
        action = new Actions(driver);
    }

    @Test
    public void shouldDiplayMoreThanSevenIphoneResultsWhenSearching() {

            WebElement searchTextBox = wait
                    .until(ExpectedConditions.elementToBeClickable(By.id("twotabsearchtextbox")));

            action.sendKeys(searchTextBox, "Celulares").sendKeys(searchTextBox, Keys.ENTER).perform();

            List<WebElement> elements = wait
                    .until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.className("sg-col-inner")));

            int count = 0;
            for (WebElement element : elements) {
                String text = element.getText();
                if (text.toLowerCase().contains("iphone"))
                    logger.info(text);
                    count++;
            }
            assertTrue(count > 70, "Expected more than 70 results, but found: " + count);
    }

    @AfterTest
    public void teardown() {
        if (driver != null) {
            driver.quit();
        }
    }
}