/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


// import javax.swing.Action;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import static org.testng.Assert.*;

import io.github.bonigarcia.wdm.WebDriverManager;

public class TitleTest{
    
    private WebDriver driver;
        
    @BeforeTest
    public void setup() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://the-internet.herokuapp.com/");
    }

    @Test
    public void shouldTitleHasTheInternetWord(){
        String title= driver.getTitle();
        assertTrue(title.contains("The Internet"));
    }

    @AfterTest
    public void teardown(){
        if (driver != null) {
            driver.quit();
        }
    }
}